config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# #-*- code:utf-8 -*-
# require 'nokogiri'
# require 'open-uri'
# # require 'rest-client'
# require 'sqlite3'
# require 'json'
# require 'timeout'

class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
   
    # Getlrc.new("http://www.kuwo.cn/geci/artist_z.htm",'z')
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])

  end
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
    #render plain: params[:article].inspect
  end
  private
  def article_params
    params.require(:article).permit(:title, :text, :name)
  end
end






class Getlrc
  # url 字母链接
  # database 字母(和数据库名字相关)： a b c ...
  def initialize(url,database)
    @nowarray  = []
    @manListId = []
    @database = database
    getManPage(url)
    getSong(url)
  end

  # 获取所有歌手的链接
  def getManPage(url)
    # 获取a b c d等
    urlId = url[31..url.length-5]
    # 获取所有manlist 放入数组
    begin
      open(uri) do |http|
        html = http.read
      end
      # html  =  RestClient.get(url).body
    rescue
      retry
    end

    doc  =  Nokogiri::HTML.parse(html)
    _lastPageUrl = doc.xpath('//*[@id="pageDiv"]/a[7]').attr('href').text
    _lastPageNum = _lastPageUrl[15..._lastPageUrl.length-4].to_i
    # 如果是其他 范围变小
    if urlId == "qita" then
      _lastPageNum = _lastPageUrl[18..._lastPageUrl.length-4].to_i
      puts _lastPageNum
    end
    (0..._lastPageNum).each do |i|
      puts "loading #{i+1}"
      getManList("http://www.kuwo.cn/geci/artist_#{urlId}_#{i}.htm")
    end
  end
  def getManList(url)
    # 获取所有歌手id  放入数组
    begin
      open(uri) do |http|
        html = http.read
      end
      # html  =  RestClient.get(url).body
    rescue
      retry
    end
    doc   =  Nokogiri::HTML.parse(html)
    doc.css('.songer_list > li').each do |li|
      str = li.>('a').attr('href').text
      str = str[26..str.length-2] # 把id号取出来放入数组 去掉这行就是把链接放入数组
      @manListId.push(str)
    end
  end

  # 获取所有歌手的歌曲 json格式
  def getSong(url)
    # 根据歌手列表每个id 获取id的所有歌曲
    @manListId.each do |manurl|
      # 获取歌手的总页数
      uri = "http://www.kuwo.cn/geci/wb/getJsonData?type=artSong&artistId=#{manurl}&page=1"
      html_response = nil
      # 处理超时异常 重新连接
      begin
        open(uri) do |http|
          html_response = http.read
        end
      rescue
        puts '超时 重新连接'
        retry
      end

      totalpage = /totalPage":[\d]+/.match(html_response).to_s.delete('totalPage":')
      #
      page = 1
      while page <= totalpage.to_i do
        uri = "http://www.kuwo.cn/geci/wb/getJsonData?type=artSong&artistId=#{manurl}&page=#{page}"
        html_response = nil

        # 处理超时异常
        begin
          open(uri) do |http|
            html_response = http.read
          end
        rescue
          puts '超时 重新连接'
          retry
        end

        allSongUrl = html_response.scan(/rid":"[\d]+/) #/rid":"[\d]+"/.match(html_response)
        allSongUrl = allSongUrl.map do |item|
          item.delete('rid":"')
        end
        allSongUrl.each do |item|
          url = "http://www.kuwo.cn/yinyue/#{item}"
          getOneLyc(url)
        end
        puts "totalpage #{totalpage}"
        puts "curruntPage #{page}"
        page = page + 1
      end

    end
    #
  end


  # 获取一首歌的歌词 存入数据库 "http://www.kuwo.cn/yinyue/6749207"
  def getOneLyc(url)
    # 读取所有歌词 放入 @data
    parseHtml(url)
    # 把 @data 插入数据库
    insert
    # sleep 1
  end


  # 解析内容
  # url       :   链接地址
  # classname :   类名
  def parseHtml(url)
    @data = {}
    @nowarray = []
    @url = url
    begin
      html  =  RestClient::Request.execute(method: :get, url: url, timeout: 60).body
    rescue
      puts '连接超时 重试'
      retry
    end

    # puts html
    doc   =  Nokogiri::HTML.parse(html)
    # 注意：： 没有获取到歌词 退出  有些页面没有歌词 以及版权问题 不显示歌词
    return if doc.css('.lrcItem').empty?
    _lrcname    = doc.xpath('//*[@id="lrcName"]').text
    _album      = doc.xpath('//*[@id="musiclrc"]/div[1]/p[1]/span/a').text
    _albumLink  = doc.xpath('//*[@id="musiclrc"]/div[1]/p[1]/span/a').attr('href')
    _artist     = doc.xpath('//*[@id="musiclrc"]/div[1]/p[2]/span/a').text
    _artistLink = doc.xpath('//*[@id="musiclrc"]/div[1]/p[2]/span/a').attr('href')
    # 传入具体歌词类名 放入数组
    doc.css('.lrcItem').each do |lyctxt|
      @nowarray.push(lyctxt.text)
    end
    # 转成字符串存入数据库
    @data["_lrcname"] = _lrcname
    @data["_album"] = _album
    @data["_albumLink"] = _albumLink.text
    @data["_artist"] = _artist
    @data["_artistLink"] = _artistLink.text
    @data["_lyccontent"] = @nowarray.join('|')
    #注意内容中的单引号等符号
    @data["_lyccontent"] = @data["_lyccontent"].gsub(/['"\\\*&.?!,…:;]/, '')
  end
  # 插入数据库
  def insert
    # 没有歌词的时候就不存入数据库
    if @data.has_key?("_lyccontent") then
      if @data["_lyccontent"].length < 20 then
        puts "#{@url}没有具体文字内容"
        return
      else
        #注意内容中的单引号等符号
        lydata = @data["_lyccontent"].gsub(/['"\\\*&.?!,…:;]/, '')
        # 根据@database的名字不同 存入不同的数据库
        SQLite3::Database.new("#{@database}.db") do |db|
          db.execute("INSERT INTO lyc ( lycname , album , albumLink , artist , artistLink , lyccontent ) VALUES ('#{@data["_lrcname"]}' , '#{@data["_album"]}' , '#{@data["_albumLink"]}' , '#{@data["_artist"]}' , '#{@data["_artistLink"]}', '#{lydata}')")
          db.close
        end
      end
    else
      # puts @data["_lyccontent"]
      return
    end
  end

end

# run = Getlrc.new("http://www.kuwo.cn/geci/artist_a.htm")
# puts run.nowarray
# 还差一个 qita 分类没有下载 用run = Getlrc.new("http://www.kuwo.cn/geci/artist_qita.htm")

# # 根据不同的字母 存入不同的数据库
# "f".each_char do |item|
#   puts " -----#{item}组开始------- "
#   Getlrc.new("http://www.kuwo.cn/geci/artist_#{item}.htm",item)
# end


# ~> -:1:in `<main>': uninitialized constant ApplicationController (NameError)

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/new.html.erb
<p>application new</p>

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>



<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <%= link_to 'New article', new_article_path %>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to '详情', article_path(article) %></td>
      <td><%= link_to '编辑', edit_article_path(article) %></td>
      <td><%= link_to '删除', article_path(article),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Higou</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>